server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/products/**
        - id: cart-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/carts/**
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
