server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: product-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/products/**
        - id: cart-service
          uri: http://localhost:8050
          predicates:
            - Path=/api/v1/carts/**
