spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://mysqldb:3306/cart_service
    username: root
    password: pass
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
queue:
  product: product
eureka:
  instance:
    appname: ${spring.application.name}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:9000/eureka
