micronaut:
  application:
    name: productService2
  server:
    port: 8086

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/product_service_dev
    username: postgres
    password: ""
    driverClassName: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop

rabbitmq:
  uri: amqp://guest:guest@localhost:5672

netty:
  default:
    allocator:
      max-order: 3
eureka:
  client:
    registration:
      enabled: true
    defaultZone: ${EUREKA_HOST:localhost}:${EUREKA_PORT:9000}
